---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: photo
  annotations:
    cert-manager.io/issuer: my-root-ca-issuer
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: photos.example.com 
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: photo-service
            port:
              number: 80
  tls:
  - hosts:
    - photos.example.com
    secretName: photo-secret
